apiVersion: v1
kind: ConfigMap
metadata:
  name: preset-mesh-config
  namespace: {{ include "osm.namespace" . }}
data:
  preset-mesh-config.json: |
    {
      "sidecar": {
        "enablePrivilegedInitContainer": {{.Values.osm.enablePrivilegedInitContainer | mustToJson}},
        "logLevel": {{.Values.osm.sidecarLogLevel | mustToJson}},
        "maxDataPlaneConnections": {{.Values.osm.maxDataPlaneConnections | mustToJson}},
        "configResyncInterval": {{.Values.osm.configResyncInterval | mustToJson}},
        "sidecarClass": {{.Values.osm.sidecarClass | mustToJson }},
        "sidecarImage": {{.Values.osm.sidecarImage | mustToJson }},
        "sidecarDrivers": {{.Values.osm.sidecarDrivers | mustToJson }},
        "localProxyMode": {{.Values.osm.localProxyMode | mustToJson}}
      },
      "traffic": {
        "enableEgress": {{.Values.osm.enableEgress | mustToJson}},
        "enablePermissiveTrafficPolicyMode": {{.Values.osm.enablePermissiveTrafficPolicy | mustToJson}},
        "outboundPortExclusionList": {{.Values.osm.outboundPortExclusionList | mustToJson}},
        "inboundPortExclusionList": {{.Values.osm.inboundPortExclusionList | mustToJson}},
        "outboundIPRangeExclusionList": {{.Values.osm.outboundIPRangeExclusionList | mustToJson}},
        "outboundIPRangeInclusionList": {{.Values.osm.outboundIPRangeInclusionList | mustToJson}},
        "networkInterfaceExclusionList": {{.Values.osm.networkInterfaceExclusionList | mustToJson}}
      },
      "observability": {
        "enableDebugServer": {{.Values.osm.enableDebugServer | mustToJson}},
        "osmLogLevel": {{.Values.osm.controllerLogLevel | mustToJson}},
        "tracing": {
          "enable": {{.Values.osm.tracing.enable | mustToJson}}{{- if .Values.osm.tracing.enable }},{{- end }}
          {{- if .Values.osm.tracing.enable }}
          "port": {{.Values.osm.tracing.port | mustToJson}},
          "address": {{include "osm.tracingAddress" . | mustToJson}},
          "endpoint": {{.Values.osm.tracing.endpoint | mustToJson}}
          {{- end }}
        },
        "remoteLogging": {
          "enable": {{.Values.osm.remoteLogging.enable | mustToJson}}{{- if .Values.osm.remoteLogging.enable }},{{- end }}
          {{- if .Values.osm.remoteLogging.enable }}
          "port": {{.Values.osm.remoteLogging.port | mustToJson}},
          "address": {{.Values.osm.remoteLogging.address | mustToJson}},
          "endpoint": {{.Values.osm.remoteLogging.endpoint | mustToJson}},
          "authorization": {{.Values.osm.remoteLogging.authorization | mustToJson}}
          {{- end }}
        }
      },
      "certificate": {
        "serviceCertValidityDuration": {{.Values.osm.certificateProvider.serviceCertValidityDuration | mustToJson}},
        {{- if .Values.contour.enabled }}
        "ingressGateway": {
          "subjectAltNames": ["osm-contour-sidecar.{{include "osm.namespace" .}}.cluster.local"],
          "validityDuration": "24h",
          "secret": {
            "name": "osm-contour-sidecar-client-cert",
            "namespace": "{{include "osm.namespace" .}}"
          }
        },
        {{- end }}
        "certKeyBitSize": {{.Values.osm.certificateProvider.certKeyBitSize | mustToJson}}
      },
      "featureFlags": {
        "enableWASMStats": {{.Values.osm.featureFlags.enableWASMStats | mustToJson}},
        "enableEgressPolicy": {{.Values.osm.featureFlags.enableEgressPolicy | mustToJson}},
        "enableSnapshotCacheMode": {{.Values.osm.featureFlags.enableSnapshotCacheMode | mustToJson}},
        "enableAsyncProxyServiceMapping": {{.Values.osm.featureFlags.enableAsyncProxyServiceMapping | mustToJson}},
        "enableIngressBackendPolicy": {{.Values.osm.featureFlags.enableIngressBackendPolicy | mustToJson}},
        "enableAccessControlPolicy": {{.Values.osm.featureFlags.enableAccessControlPolicy | mustToJson}},
        "enableSidecarActiveHealthChecks": {{.Values.osm.featureFlags.enableSidecarActiveHealthChecks | mustToJson}},
        "enableRetryPolicy": {{.Values.osm.featureFlags.enableRetryPolicy | mustToJson}}
      }
    }
